generic:
  nameOverride: alpine
  fullnameOverride: alpine

  replicaCount: 1

  image:
    repository: alpine
    pullPolicy: Always
    tag: latest

  service:
    port: 8989

  ingress:
    enabled: false

  pvc:
    enabled: false

  probes:
    initialDelaySeconds: 15

  config:
    PUID: "1000"
    PGID: "1000"
    TZ:  Europe/London
