include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'

stages:
  - renovate

renovate:
  stage: renovate
  image: ${CI_RENOVATE_IMAGE_FULL}
  variables:
    RENOVATE_EXTRA_FLAGS: henrywhitaker3/charts
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
