version: '3'

tasks:
  build:all:
    deps:
      - task: build
        vars:
          DIR: sonarr
      - task: build
        vars:
          DIR: radarr
      - task: build
        vars:
          DIR: overseerr
      - task: build
        vars:
          DIR: organizr
      - task: build
        vars:
          DIR: prowlarr
      - task: build
        vars:
          DIR: tautulli
      - task: build
        vars:
          DIR: monitorr
      - task: build
        vars:
          DIR: speedtest
      - task: build
        vars:
          DIR: transmission

  build:
    dir: ./{{ .DIR }}
    cmds:
      - |
        sed -i 's/version: "[0-9]*\.[0-9]*\.[0-9]*"/version: "{{ .VERSION }}"/g' Chart.yaml
      - helm dependency update
      - helm dependency build
