version: '3'

tasks:
  build:
    deps:
      - build:sonarr
      - build:radarr
      - build:overseerr
      - build:organizr
      - build:prowlarr
      - build:tautulli
      - build:monitorr
      - build:speedtest
      - build:transmission

  build:sonarr:
    dir: ./sonarr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:radarr:
    dir: ./radarr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:overseerr:
    dir: ./overseerr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:organizr:
    dir: ./organizr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:prowlarr:
    dir: ./prowlarr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:tautulli:
    dir: ./tautulli/
    cmds:
      - helm dependency update
      - helm dependency build

  build:monitorr:
    dir: ./monitorr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:speedtest:
    dir: ./speedtest/
    cmds:
      - helm dependency update
      - helm dependency build

  build:transmission:
    dir: ./transmission/
    cmds:
      - helm dependency update
      - helm dependency build
