version: '3'

output: prefixed

tasks:
  bump:generic:
    cmds:
      - ./scripts/bump.sh {{ .VERSION }}

  update:version:
    dir: ./{{ .DIR }}
    cmds:
      - |
        sed -i 's/version: "[0-9]*\.[0-9]*\.[0-9]*"/version: "{{ .VERSION }}"/g' Chart.yaml
      - task: build:std

  build:std:
    dir: ./{{ .DIR }}
    prefix: build:std:{{ .DIR }}
    cmds:
      - helm dependency update
      - helm dependency build

  update:argo:
    cmds:
      - helm upgrade --install -n argo -f argocd/values.yaml argo argocd/

  release:
    vars:
      VERSION:
        sh: cat generic/Chart.yaml | grep -Eo "[0-9]+[.][0-9]+[.][0-9]+$"
    cmds:
      - git tag v{{ .VERSION }}
      - git push origin v{{ .VERSION }}

  patch:pvc:
    cmds:
      - |
        kubectl patch -n {{ .NAMESPACE }} pvc {{ .NAME }} --patch '{ "metadata": { "annotations": { "meta.helm.sh/release-namespace": "{{ .NAMESPACE }}", "meta.helm.sh/release-name": "{{ .NAME }}" }, "labels": { "app.kubernetes.io/managed-by": "Helm" } } }'
