version: '3'

tasks:
  build:
    deps:
      - build:sonarr
      - build:radarr
      - build:overseerr

  build:sonarr:
    dir: ./sonarr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:radarr:
    dir: ./radarr/
    cmds:
      - helm dependency update
      - helm dependency build

  build:overseerr:
    dir: ./overseerr/
    cmds:
      - helm dependency update
      - helm dependency build
