version: '3'

tasks:
  build:
    deps:
      - build:sonarr
      - build:radarr
      - build:overseer

  build:sonarr:
    dir: ./sonarr/
    cmds:
      - helm dependency build

  build:radarr:
    dir: ./radarr/
    cmds:
      - helm dependency build

  build:overseer:
    dir: ./overseer/
    cmds:
      - helm dependency build
