apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "redeployer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "redeployer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
