apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: charts/cert-manager
    repoURL: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
