apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argo
spec:
  destination:
    namespace: authelia
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/authelia
    repoURL: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
