apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-runner
  namespace: argo
spec:
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/chart-runner
    repoURL: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
