apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-provisioner
  namespace: argo
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/mysql-provisioner
    repoURL: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
