apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kume
  namespace: argo
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: charts/uptime-kume
    repoURL: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
