secrets: vaults/Infra/items/authelia

authelia:
  domain: plexmox.com

  pod:
    kind: Deployment
    replicas: 3

  rbac:
    enabled: true

  ingress:
    enabled: true

    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    subdomain: authelia

  secret:
    existingSecret: "authelia-secrets"

  configMap:
    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true
        path: /secrets/users_database.yml

    access_control:
      default_policy: deny
      rules:
        - domain:
          - plexmox.com
          - "*.plexmox.com"
          policy: two_factor

    session:
      redis:
        enabled: true
        host: redis.databases.svc.cluster.local

    storage:
      postgres:
        enabled: false

      mysql:
        enabled: true
        host: mariadb.databases.svc.cluster.local
        port: 3306
        username: authelia
        database: authelia

    notifier:
      filesystem:
        enabled: true

      smtp:
        enabled: false
