authelia:
  domain: plexmox.com

  rbac:
    enabled: true

  ingress:
    enabled: true

    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod

    subdomain: authelia

  configMap:
    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true

    access_control:
      default_policy: deny
      rules:
        - domain:
          - plexmox.com
          - "*.plexmox.com"
          policy: two_factor

    session:
      redis:
        enabled: true
        host: authelia-redis.authelia.svc.cluster.local
