secrets:
  grafana: vaults/Infra/items/grafana-creds

kube-prometheus-stack:
  alertmanager:
    enabled: false

  nodeExporter:
    enabled: false

  grafana:
    enabled: true

    admin:
      existingSecret: grafana-creds

    ingress:
      enabled: true

      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://auth.plexmox.com/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.plexmox.com

      hosts:
        - grafana.plexmox.com

      tls:
        - secretName: grafana-plexmox-com-tls
          hosts:
            - grafana.plexmox.com

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: default
          orgId: 1
          folder: Custom
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        haproxy:
          gnetId: 2428
          revision: 7
          datasource: Prometheus
        node_exporter:
          gnetId: 1860
          revision: 31
          datasource: Prometheus
        argocd:
          gnetId: 14584
          revision: 1
          datasource: Prometheus

  prometheus:
    ingress:
      enabled: true

      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://auth.plexmox.com/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.plexmox.com

      hosts:
        - prometheus.plexmox.com

      tls:
        - secretName: prometheus-plexmox-com-tls
          hosts:
            - prometheus.plexmox.com

    persistentVolume:
      enabled: true
      size: 20Gi
      storageClass: smb

    prometheusSpec:
      retention: 7d

      additionalScrapeConfigs:
        - job_name: kubernetes-service-endpoints
          kubernetes_sd_configs:
          - role: service
          relabel_configs:

          # annotation 'prometheus.io/scrape' must be set to 'true'
          - action: keep
            regex: true
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]

          # service cannot be in kube-system or prom namespaces
          - action: drop
            regex: (kube-system|prom)
            source_labels: [__meta_kubernetes_namespace]

          # service port name must end with word 'metrics'
          - action: keep
            regex: .*metrics
            source_labels: [__meta_kubernetes_service_port_name]

          # allow override of http scheme
          - action: replace
            regex: (https?)
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            target_label: __scheme__

          # allow override of default /metrics path
          - action: replace
            regex: (.+)
            source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            target_label: __metrics_path__

          # allow override of default port
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            target_label: __address__

          - {action: labelmap, regex: __meta_kubernetes_service_label_(.+)}

          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace

          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_name

        - job_name: 'haproxy'
          static_configs:
            - targets: ['jump-k8s.lab:9101']

        - job_name: 'node_exporter'
          static_configs:
            - targets:
              - 'pihole.lab:9100'
              - 'lb-1.lab:9100'
              - 'lb-2.lab:9100'
              - 'vpn-1.lab:9100'
              - 'vpn-2.lab:9100'
              - 'jump-k8s.lab:9100'
              - 'bedroom.lab:9100'
              - 'proxmox-1.lab:9100'
              - 'proxmox-2.lab:9100'
              - 'k8s-control-1.lab:9100'
              - 'k8s-control-2.lab:9100'
              - 'k8s-control-3.lab:9100'
              - 'k8s-worker-1.lab:9100'
              - 'k8s-worker-2.lab:9100'
              - 'k8s-worker-3.lab:9100'

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: smb
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
