generic:
  nameOverride: radarr
  fullnameOverride: radarr

  replicaCount: 1

  image:
    repository: linuxserver/radarr
    pullPolicy: Always
    tag: latest

  service:
    port: 8989

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: https://plexmox.com/api/v2/auth?group=1
      nginx.ingress.kubernetes.io/auth-signin: https://plexmox.com
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter
        '</head>'
        '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/nord.css">
        </head>';
        sub_filter_once on;
    hosts:
      - host: radarr2.plexmox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: radarr2-plexmox-com-tls
      hosts:
        - radarr2.plexmox.com

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn

  depoymentStrategy: Recreate

  probes:
    initialDelaySeconds: 30

  config:
    PUID: "1000"
    GUID: "1000"
    TZ:  Europe/London

  volumes:
    - name: media
      hostPath:
        path: /plex

  volumeMounts:
    - mountPath: /data
      name: media
