{{- if .Values.vpn.enabled }}
{{- if .Values.vpn.secret.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "generic.fullname" . }}-wireguard
spec:
  itemPath: {{ .Values.vpn.secret.path }}
{{- end }}
{{- if .Values.vpn.healthcheck.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "generic.fullname" . }}-healthcheck
spec:
  itemPath: {{ .Values.vpn.healthcheck.path }}
{{- end }}
{{- end }}
