{{- if and (.Values.vpn.secret.enabled) (.Values.vpn.enabled) }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "generic.fullname" . }}-wireguard
spec:
  itemPath: {{ .Values.vpn.secret.path }}
{{- end }}
