generic:
  nameOverride: mariadb
  fullnameOverride: mariadb

  replicaCount: 1

  image:
    repository: mariadb
    pullPolicy: Always
    tag: latest

  deploymentStrategy:
    type: Recreate

  service:
    portName: mysql
    port: 3306

  secrets: vaults/Infra/items/mariadb

  ingress:
    enabled: false

  pvc:
    enabled: true
    mountPath: /var/lib/mysql
    storageClassName: longhorn
    size: 10Gi

  probes:
    type: tcpSocket
    options:
      port: mysql
