generic:
  nameOverride: organizr
  fullnameOverride: organizr

  replicaCount: 0

  image:
    repository: organizr/organizr
    pullPolicy: Always
    tag: latest

  service:
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: https://plexmox.com/api/v2/auth?group=1
      nginx.ingress.kubernetes.io/auth-signin: https://plexmox.com
    hosts:
      - host: organizr.plexmox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: organizr-plexmox-com-tls
      hosts:
        - organizr.plexmox.com

  pvc:
    enabled: true
    mountPath: /config
    storageClassName: longhorn
    size: 2Gi

  deploymentStrategy:
    type: Recreate

  probes:
    initialDelaySeconds: 30

  config:
    fpm: "true"
    branch: "dev"
    PUID: "1000"
    GUID: "1000"
    TZ:  Europe/London
