name: smb

host: //10.0.0.9/pvcs

creds:
  secretName: smb-creds
  namespace: kube-system

volumeBindingMode: Immediate

mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=none
  - noserverino
