name: smb

host: ""

creds:
  secretName: smbcreds
  namespace: default

volumeBindingMode: Immediate

mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
