projects:
  - name: cluster
    description: Things that make the cluster work
  - name: apps
    description: Our apps running in the cluster

charts:
  - name: metrics-server
    project: cluster
    namespace: kube-system
    path: charts/metrics-server
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: metallb
    project: cluster
    namespace: metallb
    path: charts/metallb
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: ingress-nginx
    project: cluster
    namespace: ingress-nginx
    path: charts/ingress-nginx
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: cert-manager
    project: cluster
    namespace: cert-manager
    path: charts/cert-manager
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: longhorn
    project: cluster
    namespace: longhorn
    path: charts/longhorn
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: gitlab-runner
    project: apps
    namespace: gitlab-runner
    path: charts/gitlab-runner
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: chart-runner
    project: apps
    namespace: gitlab-runner
    path: charts/chart-runner
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: descheduler
    project: cluster
    namespace: kube-system
    path: charts/descheduler
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: connect
    project: cluster
    namespace: 1password
    path: charts/1password
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: smb-provisioner
    project: cluster
    namespace: kube-system
    path: charts/smb-provisioner
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: sonarr
    project: apps
    namespace: media
    path: charts/sonarr
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: radarr
    project: apps
    namespace: media
    path: charts/radarr
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: overseerr
    project: apps
    namespace: media
    path: charts/overseerr
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: organizr
    project: apps
    namespace: media
    path: charts/organizr
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: prowlarr
    project: apps
    namespace: media
    path: charts/prowlarr
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: tautulli
    project: apps
    namespace: media
    path: charts/tautulli
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: speedtest
    project: apps
    namespace: misc
    path: charts/speedtest
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: transmission
    project: apps
    namespace: media
    path: charts/transmission
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: redis
    project: apps
    namespace: databases
    path: charts/redis
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: mariadb
    project: apps
    namespace: databases
    path: charts/mariadb
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: authelia
    project: apps
    namespace: authelia
    path: charts/authelia
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: kube-prometheus-stack
    project: apps
    namespace: monitoring
    path: charts/kube-prometheus-stack
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: plex
    project: apps
    namespace: media
    path: charts/plex
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: redeployer
    project: cluster
    namespace: media
    path: charts/redeployer
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: uptime-kuma
    project: apps
    namespace: monitoring
    path: charts/uptime-kuma
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: minio
    project: apps
    namespace: minio
    path: charts/minio
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true

  - name: mysql-provisioner
    project: apps
    namespace: databases
    path: charts/mysql-provisioner
    repoUrl: https://gitlab.com/henrywhitaker3/charts.git
    targetRevision: HEAD
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true
