cert-manager:
  installCRDs: true

  ingressShim:
    defaultIssuerName: letsencrypt-prod
    defaultIssuerKind: ClusterIssuer

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

cloudflareApiToken: vaults/Infra/items/cloudflare-api-token
