minio:
  existingSecret: root-creds

  ingress:
    enabled: true

    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-url: https://auth.plexmox.com/api/verify
      nginx.ingress.kubernetes.io/auth-signin: https://auth.plexmox.com

    hosts:
      - minio.plexmox.com

    tls:
      - secretName: minio-plexmox-com-tls
        hosts:
          - minio.plexmox.com

  resources:
    requests:
      memory: 2Gi

  persistence:
    enabled: true

    storageClass: smb

    size: 150Gi

rootCredsPath: vaults/Infra/items/minio-root-creds
