generic:
  nameOverride: redis
  fullnameOverride: redis

  replicaCount: 1

  image:
    repository: redis
    pullPolicy: Always
    tag: latest

  service:
    portName: redis
    port: 6379

  ingress:
    enabled: false

  pvc:
    enabled: true
    mountPath: /data
    storageClassName: longhorn
    size: 2Gi

  probes:
    type: tcpSocket
    options:
      port: redis
